apiVersion: V1
kind: Service
metadata:
  name: nginx
spec:
  selectors:
    project: expense
    module: backend
    environment: dev
  ports:
    - name: node-port
      protocol: TCP
      targetPort: 