kind: Service
apiVersion: v1

metadata:
  name: nginx-node
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
    - name: nginx-node-port
      protocol: TCP
      port: 80
      targetPort: 80