kind: Service
apiVersion: v1


metadata:
 name: nginx
spec:
 selector: 
  project: expense
  module: backend
  environment: dev
 ports:
  - name: nginx-load-balancer
    prototype: TCP
    port: 80
    targetPort: 80